---
- hosts: webservers
  become: True
  tasks:
    - name: "Install pacages"
      tags:
        - install
      apt:
        name: apache2
        state: present
    - name: "Start Apache Server"
      service:
        enabled: True
        name: apache2
        state: started
      tags:
        - start
    - copy:
        dest: /var/www/html/
        src: index.html
      name: "Deploy static website"
      tags:
        - deploy

