---
- name: Install nginx
  hosts: slave1
  remote_user: ubuntu
  become: yes
  
  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: latest
      
  - name: copy web page template
    template:
      src: index.html
      dest: /usr/share/nginx/html/index.html
      
  - name: Start nginx Services
    service:
       name: nginx
       state: started
      
