---
- name: Install nginx
  hosts: slave1
  remote_user: hugo995
  become: yes
  
  tasks:
  - name: Install nginx
    yum:
      name: nginx
      state: latest
      
  - name: copy web page template
    template:
      src: index.html
      dest: /usr/share/nginx/html/index.html
  
  - name: start nginx
    service:
       name: nginx
       state: started
      
