--- 
- 
  hosts: web:vars
  tasks: 
    - 
      apt: 
        name: nginx
        state: present
      name: "Install NginX"
    - 
      name: "Start Nginx Services"
      service: 
        name: nginx
        state: started
